### PR TITLE
Feature/main player loop

### PR DESCRIPTION
**Pull request by roygarrett**
Created function that implements main player loop and returns players that passed and did not bust

### CODE REVIEW

**Review by bennettapps — APPROVED** [review]
code is very well thought out and all the reformatting of previous code is appreciated!

**Comment by roygarrett** [comment]
> code is very well thought out and all the reformatting of previous code is appreciated!

Thank you! We will do some more reformatting in the future!

**Comment by dhale27** [comment]
Looks good! Good job at keeping it nice and concise.

**Comment by dhale27** [comment]
Looks good! Good job at keeping it nice and concise.

**Comment by roygarrett** [comment]
> Looks good! Good job at keeping it nice and concise.

Thank you! I will continue to be as precise as possible!

**Review by dhale27 — COMMENTED** [review]
Great job

**Review by dhale27 — APPROVED** [review]

**Pull request merged**
